# Generated by Django 5.0.14 on 2026-03-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('filename', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.IntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='notes.note')),
            ],
            options={
                'ordering': ['note', 'chunk_index'],
            },
        ),
    ]
